### ISSUE TITLE
Any support for Remix/Hydrogen?

### ISSUE THREAD

**Issue by Olys6** [mattmilburn/strapi-plugin-preview-button#118]
I'm looking to add preview functionality between Strapi and my Hydrogen app. Before I go too far is this possible to produce?

**Comment by mattmilburn** [comment]
Hi @Olys6 I've never personally worked with Hydrogen, but the only thing this plugin does is build a URL according to your configuration and give you a button to open that URL. If you need to query data outside of Strapi when the preview URL is built, then you may have complications because the plugin does not currently support that, but it will in the future.

Let me know if that answers your question or if you are still confused about anything 🙂
