### ISSUE TITLE
Link customization

### ISSUE THREAD

**Issue by Jacq** [mattmilburn/strapi-plugin-preview-button#12]
Hi,

I see that the format for preview links are:
https://example.com/api/preview?slug=my-page&secret=YOURSECRET
https://example.com/api/preview?slug=my-post&type=post&secret=YOURSECRET

Is it possible to do some customization in that format such as:
https://example.com/api/my-page?preview=YOURSECRET
https://example.com/api/my-post?preview=YOURSECRET

In my case I even need to use a single preview por all pages or ports so my-page and my-post will not be the current slug but a generic one:
https://example.com/api/pages?preview=YOURSECRET
https://example.com/api/posts?preview=YOURSECRET

Cheers,
Jacq

**Comment by mattmilburn** [comment]
Hi @Jacq, the `secret=YOURSECRET` part of the URL only applies to the draft URL because it may be showing non-public content when being viewed.

I've recently updated the plugin to support more flexible URLs for draft and published URLs. It also has support for single types. Let me know if this helps you out 👍🏻

**Comment by Jacq** [comment]
Thanks @mattmilburn ! with the new basePath flexibility I can produce the URLs I need with just:

contentTypes: [
  {
            uid: 'api::post.post',
            published: {
              basePath: 'blogs/?preview=<TOKEN>',
            },
          },
  }
]
