### ISSUE TITLE
unable to resolve dependency tree - strapi 4.2.0 - preview button 0.3.4

### ISSUE THREAD

**Issue by Matt-roki** [mattmilburn/strapi-plugin-preview-button#31]
Getting the following error on the latest version of strapi

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: roki-cms@1.0.0
npm ERR! Found: @strapi/icons@0.0.1-alpha.79
npm ERR! node_modules/@strapi/icons
npm ERR!   peer @strapi/icons@"^0.0.1-alpha.73" from @strapi/design-system@1.1.1
npm ERR!   node_modules/@strapi/design-system
npm ERR!     peer @strapi/design-system@"^1.1.0" from strapi-plugin-preview-button@0.3.4
npm ERR!     node_modules/strapi-plugin-preview-button
npm ERR!       strapi-plugin-preview-button@"0.3.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/icons@"^1.1.0" from strapi-plugin-preview-button@0.3.4
npm ERR! node_modules/strapi-plugin-preview-button
npm ERR!   strapi-plugin-preview-button@"0.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by mattmilburn** [comment]
Hi @Matt-roki Sorry for the late response. I'm not sure which version of Strapi you are referring to, but there was a version of Strapi that had a problem with the `@strapi/icons` and `@strapi/design-system` being peer dependencies which led to failed builds.

I raised this as an [issue #627](https://github.com/strapi/design-system/issues/627) with Strapi and it has since been resolved since v4.2.3 and should not be happening anymore.

Can you confirm after you have both Strapi and the preview button plugin updated to their latest versions?

**Comment by Matt-roki** [comment]
> 

This issue was based on 4.2.0. I ended up making my own preview button that works with the version contenting plugin. Thanks tho :)
