### ISSUE TITLE
Option to show both "preview" and "live" open buttons

### ISSUE THREAD

**Issue by ecosse3** [mattmilburn/strapi-plugin-preview-button#57]
Hi,

I would really appreciate showing both "preview" and "live" open buttons option when content is already published. When using Strapi with SSR content is published by making a deployment manually and then content user would be able to view draft state which is not yet published (even when editing already "published" content).

It could just add a button:
![image](https://user-images.githubusercontent.com/17691791/194319176-7929a279-3ba9-4450-861c-3fb1d5977ad0.png)

What do you think about that? Thanks

**Comment by mattmilburn** [comment]
Hi @ecosse3 That is a great point! Currently the plugin does not work that way but I agree it should be made possible. I'll keep you updated as I include that new feature. 👍🏻 

**Just a side note** - In the future, Strapi will change how it handles draft/publish states by implementing a more advanced and "true" draft system. In other words, we will one day be working with multiple draft versions of an entity rather than an on/off draft state. Once that happens I'm sure this plugin will need a significant update.

**Comment by Mcastres** [comment]
Hey 👋 Curious to know the status of this feature :)

**Comment by mattmilburn** [comment]
Hi @Mcastres I'm currently doing lots of house keeping with my Strapi plugins and the preview button is certainly one of them. Expect this feature in this month of August 2023 👍🏻 I'll ping everyone on this issue when it is released 🙂

**Comment by mattmilburn** [comment]
Hi @ecosse3 @Mcastres  This plugin has now been upgraded to [version 2.0.0](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v2.0.0) with breaking changes to the configuration and a lot of improvements behind the scenes.

This includes the new `draft.alwaysVisible` option that was requested on this issue. Please let me know how it goes for you and see the [migration guide](https://github.com/mattmilburn/strapi-plugin-preview-button/blob/v2.0.0/MIGRATION.md) before upgrading.

**Comment by ecosse3** [comment]
@mattmilburn This works great for me! Thank you so much!

**Comment by Mcastres** [comment]
Awesome! Thanks @mattmilburn 🔥
