### ISSUE TITLE
Nothing appears to show on strapi 4.4.5

### ISSUE THREAD

**Issue by cherring07** [mattmilburn/strapi-plugin-preview-button#66]
Nothing appears to show on the content manager view for Example Blog when I have the following added to plugins,ts. Am I missing an installation step?
```
 "preview-button": {
      config: {
        contentTypes: [
          {
            uid: "api::example-blog.example-blog",
            draft: {
              url: "http://localhost:1337/api/preview",
              query: {
                type: "post",
                id: "{slug}",
              },
            }
          },
        ],
      },
    },
```

**Comment by truesri** [comment]
Did you try rebuilding the admin by running `yarn build`?

**Comment by mattmilburn** [comment]
Hi @cherring07 Your plugin config looks okay to me. One thing to consider is this plugin will currently display the preview button only when the entity is in draft mode. Once it is in published mode it will show the live buttons. However, because you did not provide the published URL config, it won't show a live button when in published mode.

Is that possibly the issue you are having?

**Comment by cherring07** [comment]
Thanks for replies...`npm run build` solved it.

I opened a PR with this added to the readme.md
